stages:
  - backup

backup_to_nextcloud:
  stage: backup
  script:
    - apt-get update -qy
    - apt-get install -y zip curl
    - cd $CI_PROJECT_DIR
    - zip -r $CI_COMMIT_SHA.zip . -x '.git/*'
    - curl -X PUT -u $NEXTCLOUD_USERNAME:$NEXTCLOUD_PASSWORD -T $CI_COMMIT_SHA.zip -g $NEXTCLOUD_URL/remote.php/dav/files/$NEXTCLOUD_USERNAME/$NEXTCLOUD_PATH/$CI_COMMIT_SHA.zip
    - rm $CI_COMMIT_SHA.zip
  only:
    - main
